

services:
  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - user-service
      - order-service
    environment:
      DATABASE_URL: postgresql://gateway_user:gateway_password@postgres:5432/gateway_db
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
  postgres:
    image: postgres:16
    container_name: gateway-postgres
    environment:
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_password
      POSTGRES_DB: gateway_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gateway-redis
    ports:
      - "6379:6379"

  user-service:
    build: ./mock-user-service
    expose:
      - "8001"
    deploy:
      replicas: 2

  order-service:
    build: ./mock-order-service
    container_name: order-service
    ports:
      - "8002:8002"

  nginx:
    image: nginx:latest
    container_name: gateway-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - gateway

volumes:
  postgres_data: